# Generated by Django 3.0.1 on 2019-12-27 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('date', models.DateField(default=datetime.datetime(2019, 12, 27, 6, 30, 51, 559977, tzinfo=utc))),
                ('river', models.CharField(choices=[('list', 0), ('of', 1), ('rivers', 2)], max_length=50)),
                ('flow', models.FloatField()),
                ('description', models.TextField(max_length=250)),
                ('piblic', models.BooleanField(default=False)),
            ],
        ),
    ]
