# Generated by Django 3.0.1 on 2020-01-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20191227_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='piblic',
            new_name='public',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='river',
            field=models.CharField(choices=[(0, 'list'), (1, 'of'), (2, 'rivers')], max_length=50),
        ),
    ]
