# Generated by Django 3.0.1 on 2020-01-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200118_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='river',
            field=models.CharField(max_length=50),
        ),
    ]
